name: Set .bioc inputs
on:
  workflow_dispatch: {}
  push:
    paths:
      - logs/*/copied
jobs:
  biocset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          persist-credentials: true


      - name: Copy old run
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 50
          shell: bash
          command: |
            set -x
            git config --global --add safe.directory "$GITHUB_WORKSPACE"
            git pull origin main || git reset --hard origin/main
            git remote add template https://github.com/Bioconductor/gha-bbs
            git pull template || true
            git checkout template/main -- .github
            cat PLATFORM.bioc > platform
            sanitizedplatform=$(cat platform | sed "s/[^[:alnum:]]/-/g")
            ls | grep ".bioc$" | awk -F'.bioc' '{print $1}' | xargs -i bash -c 'grep -irl "&bioc.{}" .github/ | xargs --no-run-if-empty sed -i "s#&bioc.{}#$(cat {}.bioc)#g" '
            echo "$(TZ=EST date '+%Y-%m-%d-%H-%M')" > last_bioc_set
            git config --global --add safe.directory "$GITHUB_WORKSPACE"
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .github
            git add platform
            git add last_bioc_set
            git commit -m "Auto set &bioc.* variables"
            git push

